<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Home;

class CreateHomeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Home::create([
             'logo'                         =>  'logo_sticky.svg',
             'sec_1_heading'                =>  'Papa Nadox Kitchen',
             'sec_1_paragraph'              =>  'Lorem ipsum dolor sit amet consectetur adipisicing.',
             'sec_1_heading1'               =>  '+94 423-23-221',
             'sec_1_heading2'               =>  'info@papanadoxkitchen.com',
             'sec_1_heading3'               =>  '1 Kitson Road, SE5 7LF, London',
             'sec_1_heading4'               =>  'Section 1 Heading4',
             'sec_1_right_img'              =>  '1652340272.jpg',
             'sec_2_heading'                =>  'What do you want to do',
             'sec_2_paragraph'              =>  'Choose how you would like to order below or click through to view our menu.',
             'sec_2_img1'                   =>  'how_2.svg',
             'sec_2_heading_1'              =>  'Delivery',
             'sec_2_paragraph_1'            =>  'Place an order for delivery to your house.',
             'sec_2_img_2'                  =>  'how_1.svg',
             'sec_2_heading_2'              =>  'Collection',
             'sec_2_paragraph_2'            =>  'Place an order for collection from our restaurant.',
             'sec_2_img_3'                  =>  'how_3.svg',
             'sec_2_heading_3'              =>  'Table Service',
             'sec_2_paragraph_3'            =>  'Dine-in customers only.',
             'sec3_card1_img1'              =>  'how_3.svg',
             'sec3_card1_heading1'          =>  'Easly Order',
             'sec3_card1_paragraph1'        =>  'Faucibus ante, in porttitor tellus blandit et. Phasellus tincidunt metus lectus sollicitudin.',
            //  'sec3_card2_img2'              =>  '1652340272.jpg',
             'sec3_card2_img2'              =>  'how_2.svg',
             'sec3_card2_heading2'          =>  'Quick Delivery',
             'sec3_card2_paragraph2'        =>  'Maecenas pulvinar, risus in facilisis dignissim, quam nisi hendrerit nulla, id vestibulum.',
             'sec3_card3_img3'              =>  'how_1.svg',
             'sec3_card3_heading3'          =>  'Enjoy Food',
             'sec3_card3_paragraph3'        =>  'Morbi convallis bibendum urna ut viverra. Maecenas quis consequat libero, a feugiat eros.',
             'sec3_right_header_heading'    =>  'Opening Hours',
             'sec3_right_header_paragraph'  =>  'Our opening hours varies during holidays periods, please check our website for more details.',
             'sec3_title1'                  =>  'Delivery',
             'sec3_delivery_Stime'          =>  '09:00',
             'sec3_delivery_Etime'          =>  '22:30',
             'delivery_status'              =>  '0',
             'sec3_title2'                  =>  'Collection',
             'sec3_collection_Stime'        =>  '09:00',
             'sec3_collection_Etime'        =>  '22:30',
             'collection_status'            =>  '0',
             'sec3_title3'                  =>  'Table Service',
             'sec3_right_service_Stime'     =>  '09:00',
             'sec3_table_service_Etime'     =>  '17:30',
             'table_service_status'         =>  '0',
             'status_1'                     =>  '1',
             'sec4_header1'                 =>  'Delivery Information',
             'sec4_card1_heading_1'         =>  'We provide delivery during our open hours (below).',
             'sec4_card1_paragraph_1'       =>  'We deliver to addresses within 5 miles of our store.
             We deliver to addresses within the following postcodes SE1,SE2,SE3.
             Our minimum spend for delivery is £10.00.
             Our delivery charge is £2.50.
             Free delivery when you spend at least £15.00.
             A service charge of £2.50 is applied to all orders.',
             'sec4_card1_heading_2'         =>  'Delivery Hours',
             'sec4_card1_day1'              =>  'Monday',
             'sec4_card1_day1_Stime'        =>  '12:20',
             'sec4_card1_day1_Etime'        =>  '1:20',
             'status_card1_day1'            =>  '0',
             'sec4_card1_day2'              =>  'Tuesday',
             'sec4_card1_day2_Stime'        =>  '10:20',
             'sec4_card1_day2_Etime'        =>  '11:20',
             'status_card1_day2'            =>  '0',
             'sec4_card1_day3'              =>  'Wednesday',
             'sec4_card1_day3_Stime'        =>  '10:20',
             'sec4_card1_day3_Etime'        =>  '11:20',
             'status_card1_day3'            =>  '0',
             'sec4_card1_day4'              =>  'Thursday',
             'sec4_card1_day4_Stime'        =>  '10:20',
             'sec4_card1_day4_Etime'        =>  '11:20',
             'status_card1_day4'            =>  '0',
             'sec4_card1_day5'              =>  'Friday',
             'sec4_card1_day5_Stime'        =>  '10:20',
             'sec4_card1_day5_Etime'        =>  '11:20',
             'status_card1_day5'            =>  '0',
             'sec4_card1_day6'              =>  'Saturday',
             'sec4_card1_day6_Stime'        =>  '10:20',
             'sec4_card1_day6_Etime'        =>  '11:20',
             'status_card1_day6'            =>  '0',
             'sec4_card1_day7'              =>  'Sunday',
             'sec4_card1_day7_Stime'        =>  '10:20',
             'sec4_card1_day7_Etime'        =>  '11:20',
             'status_card1_day7'            =>  '0',
             'status_2'                     =>  '1',
             'sec4_header2'                 =>  'Collection Information',
             'sec4_card2_heading_1'         =>  'We allow collection during our open hours (below).',
             'sec4_card2_paragraph_1'       =>  'Our minimum spend for collection is £8.00.
             A service charge of £2.50 is applied to all orders.',
             'sec4_card2_heading_2'         =>  'Collection Hours',
             'sec4_card2_day1'              =>  'Monday',
             'sec4card2_day1_Stime'         =>  '10:20',
             'sec4_card2_day1_Etime'        =>  '11:20',
             'status_card2_day1'            =>  '0',
             'sec4_card2_day2'              =>  'tuesday',
             'sec4_card2_day2_Stime'        =>  '10:20',
             'sec4_card2_day2_Etime'        =>  '11:20',
             'status_card2_day2'            =>  '0',
             'sec4_card2_day3'              =>  'Wednesday',
             'sec4_card2_day3_Stime'        =>  '10:20',
             'sec4_card2_day3_Etime'        =>  '11:20',
             'status_card2_day3'            =>  '0',
             'sec4_card2_day4'              =>  'Thursday',
             'sec4_card2_day4_Stime'        =>  '10:20',
             'sec4_card2_day4_Etime'        =>  '11:20',
             'status_card2_day4'            =>  '0',
             'sec4_card2_day5'              =>  'Friday',
             'sec4_card2_day5_Stime'        =>  '10:20',
             'sec4_card2_day5_Etime'        =>  '11:20',
             'status_card2_day5'            =>  '0',
             'sec4_card2_day6'              =>  'Saturday',
             'sec4_card2_day6_Stime'        =>  '10:20',
             'sec4_card2_day6_Etime'        =>  '11:20',
             'status_card2_day6'            =>  '0',
             'sec4_card2_day7'              =>  'sunday',
             'sec4_card2_day7_Stime'        =>  '10:20',
             'sec4_card2_day7_Etime'        =>  '11:20',
             'status_card2_day7'            =>  '0',
             'status_3'                     =>  '1',
             'sec4_header3'                 =>  'Table Service Information',
             'sec4_card3_heading_1'         =>  'We allow table ordering during our open hours (below).',
             'sec4_card3_paragraph_1'       =>  'Our minimum spend for table ordering is £2.50.
             A service charge of £1.00 is applied to all orders.',
             'sec4_card3_heading_2'         =>  'Table Service Hours',
             'sec4_card3_day1'              =>  'Monday',
             'sec4_card3_day1_Stime'        =>  '10:20',
             'sec4_card3_day1_Etime'        =>  '10:20',
             'status_card3_day1'            =>  '0',
             'sec4_card3_day2'              =>  'Tuesday',
             'sec4_card3_day2_Stime'        =>  '10:20',
             'sec4_card3_day2_Etime'        =>  '10:20',
             'status_card3_day2'            =>  '0',
             'sec4_card3_day3'              =>  'Wednesday',
             'sec4_card3_day3_Stime'        =>  '10:20',
             'sec4_card3_day3_Etime'        =>  '10:20',
             'status_card3_day3'            =>  '0',
             'sec4_card3_day4'              =>  'Thursday',
             'sec4_card3_day4_Stime'        =>  '10:20',
             'sec4_card3_day4_Etime'        =>  '10:20',
             'status_card3_day4'            =>  '0',
             'sec4_card3_day5'              =>  'Friday',
             'sec4_card3_day5_Stime'        =>  '10:20',
             'sec4_card3_day5_Etime'        =>  '10:20',
             'status_card3_day5'            =>  '0',
             'sec4_card3_day6'              =>  'Saturday',
             'sec4_card3_day6_Stime'        =>  '10:20',
             'sec4_card3_day6_Etime'        =>  '10:20',
             'status_card3_day6'            =>  '0',
             'sec4_card3_day7'              =>  'sunday',
             'sec4_card3_day7_Stime'        =>  '10:20',
             'sec4_card3_day7_Etime'        =>  '10:20',
             'status_card3_day7'            =>  '0',
             'sec_1_heading5'               =>  'Section 1 Heading5',
             'sec_1_heading6'               =>  'Section 1 Heading6',
             'sec_1_heading7'               =>  'Section 1 Heading7',
             'sec_1_heading8'               =>  'Section 1 Heading8',
             'sec_1_heading9'               =>  'Section 1 Heading9',
             'sec_1_heading10'              =>  'Section 1 Heading10',
             'sec_1_heading11'              =>  'Section 1 Heading11',
             'sec_2_card_1_status'          =>  '1',
             'sec_2_card_2_status'          =>  '1',
             'sec_2_card_3_status'          =>  '1',
             'sec_3_card_1_status'          =>  '1',
             'sec_3_card_2_status'          =>  '1',
             'sec_3_card_3_status'          =>  '1'
        ]);
    }
}
